name: Pull Request Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Get commit message
        id: commit-message
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1)
          echo "::set-output name=message::$COMMIT_MESSAGE"

      - name: Run commitlint
        run: echo "${{steps.commit-message.outputs.message}}" | pnpx commitlint
