name: Validate Squash Commit Message

on:
  issue_comment:
    types: [created, edited]
  pull_request_review:
    types: [submitted, edited]

jobs:
  commitlint:
    if: github.event.issue.pull_request != '' #Ensuring this runs only for PRs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [20.12.2]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Extract Proposed Cmmit Message
        id: extract-message
        run: |
          MESSAGE=%(jq -r ".comment.body" <<< "${{toJSON(github.event.comment) }}" | grep '^SQUASH COMMIT:' | cut -d':' -f2-)
          if [-z "$MESSAGE"]; then
            echo "No commit message proposal found."
            exit 78 # Neutral exit
          fi
          echo "::set-output name=message::$MESSAGE"

      - name: Run commitlint
        run: echo "${{steps.commit-message.outputs.message}}" | pnpx commitlint
